---
title: "PS4: Spatial"
author: "Maryell Abella & Sarah Kim" 
date: "11/2/2024"
format: pdf
geometry: margin=1in
fontsize: 12pt
execute:
  eval: false
  echo: true
---

**PS4:** Due Sat Nov 2 at 5:00PM Central. Worth 100 points. 

## Style Points (10 pts)

## Submission Steps (10 pts)
1. This problem set is a paired problem set.
2. Play paper, scissors, rock to determine who goes first. Call that person Partner 1.
• Partner 1 (name and cnet ID): Maryell Abella, maryell
• Partner 2 (name and cnet ID): Sarah Kim, sarahk1
3. Partner 1 will accept the ps4 and then share the link it creates with their partner.
You can only share it with one partner so you will not be able to change it after your
partner has accepted.
4. “This submission is our work alone and complies with the 30538 integrity policy.” Add
your initials to indicate your agreement: **MA** **SK**
5. “I have uploaded the names of anyone else other than my partner and I worked with
on the problem set here” (1 point)
6. Late coins used this pset: **0** Late coins left after submission: **4**
7. Knit your ps4.qmd to an PDF file to make ps4.pdf,
• The PDF should not be more than 25 pages. Use head() and re-size figures when
appropriate.
8. (Partner 1): push ps4.qmd and ps4.pdf to your github repo.
9. (Partner 1): submit ps4.pdf via Gradescope. Add your partner on Gradescope.
10. (Partner 1): tag your submission in Gradescope

Policy Background
Hospital closures have been on the rise in recent years. A hospital closure can have significant
public health implications as they can increase travel distances for patients and reduce access
to critical care, especially for already-vulnerable populations. Before starting, please read
this issue brief from the Kaiser Family Foundation (link) to understand the broader social
and policy context. We will first look at closures nationally and then focus on Texas, a
state with large urban metro areas but also with a substantial share of population living in

## Download and explore the Provider of Services (POS) file (10 pts)

```{python}
import pandas as pd
import altair as alt
alt.renderers.enable("png")
import time
import warnings 
warnings.filterwarnings('ignore')
```


1. (Partner 1) This is a fairly large dataset and we won’t be using most of the variables.
Read through the rest of the problem set and look through the data dictionary to
identify which variables you will need to complete the exercise, and use the tool on
data.cms.gov into restrict to those variables (“Manage Columns”) before exporting
(“Export”). Download this for 2016 and call it pos2016.csv. What are the variables
you pulled?

The variables pulled were: 
Categories: PRVDR_CTGRY_SBTYP_CD 
  Identifies the subtype of the provider,
Type of Provider: PRVDR_CTGRY_CD 
  Identifies the type of provider
CMS certification number: PRVDR_NUM
  CMS Certification Number
Termination Code: PGM_TRMNTN_CD 
  Indicates the current termination status for the provider.
Termination Date: TRMNTN_EXPRTN_DT
  Date the provider was terminated.
Facility Name: FAC_NAME 
Zip Code: ZIP_CD
State Code: STATE_CD 


2. (Partner 1) Import your pos2016.csv file. We want to focus on short-term hospitals.
These are identified as facilities with provider type code 01 and subtype code 01.
Subset your data to these facilities. How many hospitals are reported in this data?
Does this number make sense? Cross-reference with other sources and cite the number
you compared it to. If it differs, why do you think it could differ?

```{python}
import os
path = r'/Users/maryell/Desktop/Python II/'
```

```{python}
file_2016 = 'pos2016.csv'
absolute_path_2016 = os.path.join(path, file_2016)
df_2016 = pd.read_csv(absolute_path_2017)

short_hospitals_2016 = df_2016[(df_2016['PRVDR_CTGRY_CD'] == 1) & (df_2016['PRVDR_CTGRY_SBTYP_CD'] == 1)]
hospitals_2016 = short_hospitals_2016['PRVDR_NUM'].nunique()
hospitals_2016
```


3. (Partner 1) Repeat the previous 3 steps with 2017Q4, 2018Q4, and 2019Q4 and then
append them together. Plot the number of observations in your dataset by year.

```{python}
file_2017 = 'pos2017.csv'
absolute_path_2017 = os.path.join(path, file_2017)
df_2017 = pd.read_csv(absolute_path_2017)

short_hospitals_2017 = df_2017[(df_2017['PRVDR_CTGRY_CD'] == 1) & (df_2017['PRVDR_CTGRY_SBTYP_CD'] == 1)]
hospitals_2017 = short_term_hospitals['PRVDR_NUM'].nunique()
hospitals_2017
```

```{python}
file_2018 = 'pos2018.csv'
absolute_path_2018 = os.path.join(path, file_2018)

"""Fixing issue with text encoding"""
df_2018 = pd.read_csv(absolute_path_2018, encoding='ISO-8859-1')  

short_hospitals_2018 = df_2018[(df_2018['PRVDR_CTGRY_CD'] == 1) & (df_2018['PRVDR_CTGRY_SBTYP_CD'] == 1)]
hospitals_2018 = short_hospitals_2018['PRVDR_NUM'].nunique()
hospitals_2018
```

```{python}
file_2019 = 'pos2019.csv'
absolute_path_2019 = os.path.join(path, file_2019)

"""Fixing issue with text encoding"""
df_2019 = pd.read_csv(absolute_path_2019, encoding='ISO-8859-1')

short_hospitals_2019 = df_2019[(df_2019['PRVDR_CTGRY_CD'] == 1) & (df_2019['PRVDR_CTGRY_SBTYP_CD'] == 1)]
hospitals_2019 = short_hospitals_2019['PRVDR_NUM'].nunique()
hospitals_2019
```


```{python}
"""List to append data"""
all_hospitals = []

"""Adding year column to each dataframe"""
short_hospitals_2016['Year'] = 2016
all_hospitals.append(short_hospitals_2016)

short_hospitals_2017['Year'] = 2017 
all_hospitals.append(short_hospitals_2017)

short_hospitals_2018['Year'] = 2018
all_hospitals.append(short_hospitals_2018)

short_hospitals_2019['Year'] = 2019  
all_hospitals.append(short_hospitals_2019)

"""Appending"""
combined_hospitals = pd.concat(all_hospitals, ignore_index=True)

print(combined_hospitals.head())
```


```{python}
hospitals_by_year = combined_hospitals.groupby('Year').size().reset_index(name='Count')

all_hospitals_chart = alt.Chart(hospitals_by_year).mark_bar().encode(
    x=alt.X('Year:O'),
    y=alt.Y('Count:Q'),
    color='Year:O'
).properties(
    title='Number of Observations by Year',
)

all_hospitals_chart
```


4. Each hospital is identified by its CMS certification number. Plot the
number of unique hospitals in your dataset per year. Compare this to your plot in the
previous step. What does this tell you about the structure of the data?

```{python}
cms_by_year = combined_hospitals.groupby('Year')['PRVDR_NUM'].nunique().reset_index(name='CMS Count')

cms_hospitals_chart = alt.Chart(cms_by_year).mark_bar().encode(
    x=alt.X('Year:O'),
    y=alt.Y('CMS Count:Q'),
    color='Year:O'
).properties(
    title='Number of Unique Hospitals by Year',
)

cms_hospitals_chart
```


## Identify hospital closures in POS file (15 pts) (*)
We will now use the 2016-2019 files to identify hospital closures nationally. A hospital is
suspected to have closed if its Termination Code in the POS file lists them as an “Active
Provider” in 2016 and then they are either not active or do not appear in the data at all in
a subsequent year.

1. (Partner 2) Use this definition to create a list of all hospitals that were active in 2016
that were suspected to have closed by 2019. Record the facility name and zip of each
hospital as well as the year of suspected closure (when they become terminated or
disappear from the data). How many hospitals are there that fit this definition?

2. (Partner 2) Sort this list of hospitals by name and report the names and year of
suspected closure for the first 10 rows.

3. (Partner 2) However, not all suspected hospital closures are true closures. For example,
in the case of a merger, a CMS certification number will be appear to be “terminated,”
but then the hospital re-appear under a similar name/address with a new CMS certification
number in the next year. As a first pass to address this, remove any suspected
hospital closures that are in zip codes where the number of active hospitals does not
decrease in the year after the suspected closure.
i. Among the suspected closures, how many hospitals fit this definition of potentially
being a merger/acquisition? After correcting for this, how many hospitals do you
have left?
ii. Sort this list of corrected hospital closures by name and report the first 10 rows.

## Download Census zip code shapefile (10 pt) 

1. 1. (Partner 1) This is non-tabular data. What are the five file types? What type of
information is in each file? It will be useful going forward to have a sense going
forward of which files are big versus small. After unzipping, how big is each of the
datasets?

2. (Partner 1) Load the zip code shapefile and restrict to Texas zip codes. (Hint: you
can identify which state a zip code is in using the first 2-3 numbers in the zip code
(Wikipedia link). Then calculate the number of hospitals per zip code in 2016 based
on the cleaned POS file from the previous step. Plot a choropleth of the number of
hospitals by zip code in Texas.

## Calculate zip code’s distance to the nearest hospital (20 pts) (*)

1. (Partner 2) Create a GeoDataFrame for the centroid of each zip code nationally:
zips_all_centroids. What are the dimensions of the resulting GeoDataFrame?
What do each of the columns mean?

2. (Partner 2) Create two GeoDataFrames as subsets of zips_all_centroids. First,
create all zip codes in Texas: zips_texas_centroids. Then, create all zip codes in
Texas or a bordering state: zips_texas_borderstates_centroids, using the zip code
prefixes to make these subsets. How many unique zip codes are in each of these subsets?
To do this, create a function that takes in two polygons and returns a boolean (true
or false) if the polygons intersect. Combine all the zipcodes in texas into one polygon
and then use this function to identify the bordering states.

3. (Partner 2) Then create a subset of zips_texas_borderstates_centroids that contains
only the zip codes with at least 1 hospital in 2016. Call the resulting Geo-
DataFrame zips_withhospital_centroids What kind of merge did you decide to do,
and what variable are you merging on?

4. (Partner 2) For each zip code in zips_texas_centroids, calculate the distance to the
nearest zip code with at least one hospital in zips_withhospital_centroids.
a. This is a computationally-intensive join. Before attempting to do the entire join,
subset to 10 zip codes in zips_texas_centroids and try the join. How long did
it take? Approximately how long do you estimate the entire procedure will take?
b. Now try doing the full calculation and time how long it takes. How close is it to
your estimation?
c. Look into the .prj file and report which unit it is in. Convert the given unit to
miles, using an appropriate conversion you find online (estimates are okay).

5. (Partner 2) Calculate the average distance to the nearest hospital for each zip code in
Texas. What unit is this in? Report the average distance in miles. Does this value
make sense? Map the value for each zip code.

## Effects of closures on access in Texas (15 pts)

1. (Partner 1) Using the corrected hospital closures dataset from the first section, create
a list of directly affected zip codes in Texas – that is, those with at least one closure in
2016-2019. Display a table of the number of zip codes vs. the number of closures they
experienced.

2. (Partner 1) Plot a choropleth of which Texas zip codes were directly affected by a
closure in 2016-2019 – there was at least one closure within the zip code. How many
directly affected zip codes are there in Texas?

3. (Partner 1) Then identify all the indirectly affected zip codes: Texas zip codes within a
10-mile radius of the directly affected zip codes. To do so, first create a GeoDataFrame
of the directly affected zip codes. Then create a 10-mile buffer around them. Then, do
a spatial join with the overall Texas zip code shapefile. How many indirectly affected
zip codes are there in Texas?

4. (Partner 1) Make a choropleth plot of the Texas zip codes with a different color for
each of the 3 categories: directly affected by a closure, within 10 miles of closure but
not directly affected, or not affected.

## Reflecting on the exercise (10 pts) 

(Partner 1) The “first-pass” method we’re using to address incorrectly identified closures
in the data is imperfect. Can you think of some potential issues that could arise
still and ways to do a better job at confirming hospital closures?

(Partner 2) Consider the way we are identifying zip codes affected by closures. How
well does this reflect changes in zip-code-level access to hospitals? Can you think of
some ways to improve this measure?